name: mlflow-396ff1fa10bc8d9bfa6eb8cb6714baa6a3f3067c
channels:
  - conda-forge
dependencies:
  - argh=0.26.2=pyh9f0ad1d_1002
  - brotlipy=0.7.0=py39h5161555_1001
  - ca-certificates=2021.5.30=h4653dfc_0
  - certifi=2021.5.30=py39h2804cbe_0
  - cffi=1.14.6=py39h52b1de0_1
  - chardet=4.0.0=py39h2804cbe_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py39h2804cbe_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py39h73257c9_0
  - docker-pycreds=0.4.0=py_0
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - libblas=3.9.0=11_osxarm64_openblas
  - libcblas=3.9.0=11_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libffi=3.4.2=hbdafb3b_4
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=11_osxarm64_openblas
  - libopenblas=0.3.17=openmp_h5dd58f0_1
  - libprotobuf=3.18.0=hccf11d3_1
  - llvm-openmp=12.0.1=hf3c4609_1
  - ncurses=6.2=h9aa5885_4
  - numpy=1.21.2=py39h1f3b974_0
  - nvidia-ml=7.352.0=py_0
  - openssl=1.1.1l=h3422bc3_0
  - pandas=1.2.3=py39ha4bedbf_0
  - pathtools=0.1.2=py_1
  - pip=21.2.4=pyhd8ed1ab_0
  - promise=2.2.1=py_0
  - protobuf=3.18.0=py39hfb83b0d_0
  - psutil=5.8.0=py39h5161555_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h2804cbe_3
  - python=3.9.7=h54d631c_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h5161555_1
  - readline=8.1=hedafd6a_0
  - requests=2.26.0=pyhd8ed1ab_0
  - scikit-learn=0.24.1=py39hb966dd2_0
  - scipy=1.7.0=py39h5060c3b_0
  - sentry-sdk=1.4.3=pyhd8ed1ab_0
  - setuptools=58.0.4=py39h2804cbe_2
  - shortuuid=1.0.1=py_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.36.0=h72a2b83_2
  - subprocess32=3.5.4=py_1
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=he1e0b03_1
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wandb=0.12.1=pyhd8ed1ab_0
  - watchdog=0.9.0=py_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - zlib=1.2.11=hee7b306_1011
prefix: /Users/obara/miniforge3/envs/mlflow-396ff1fa10bc8d9bfa6eb8cb6714baa6a3f3067c
